### ISSUE TITLE
Cleaner

### ISSUE THREAD

**Issue by EnthusiastAnon** [martinlindhe/subtitles#1]
Hello good sir,

I've stumbled upon this

https://github.com/martinlindhe/subtitles/blob/master/cleaner.go

and it seems to be a program that removes advertisement from subtitles?

Now, how do I go about using this piece of software of yours?
Can I somehow make it an executable, open a .srt file with it, let it do it's magic and save the cleaned of advertisement .srt?

Thanks in advance!

@martinlindhe

**Comment by martinlindhe** [comment]
Hello, was there nothing to report?

**Comment by EnthusiastAnon** [comment]
There was nothing to report, sorry man.
I needed help for your program and asked here and then I felt ashamed for asking help here and I felt guilty and I removed the comment. I'm so sorry, I'm new to GitHub and now I see there is no way to delete the "issue".
In case you wanna help out a newbie, I asked for help here
https://reddit.com/r/techsupport/comments/7oxzx2/how_to_use_the_code_from_github_to_run_an/

**Comment by martinlindhe** [comment]
No worries at all.

I will publish binaries for this software, it will make it much easier for you to use!

**Comment by EnthusiastAnon** [comment]
That would be wonderful <3

**Comment by martinlindhe** [comment]
You can find executables for Windows and macOS over at https://github.com/martinlindhe/subtitles/releases

I hope that is one of the operating systems you use!

**Comment by martinlindhe** [comment]
I also posted on your reddit thread. Please let me know if you have more questions, don't be afraid to ask!
