### ISSUE TITLE
WebVTT cue timing parsing is not correct

### ISSUE THREAD

**Issue by chen-chao** [martinlindhe/subtitles#4]
See [WebVTT cue timings and settings parsing](https://www.w3.org/TR/webvtt1/#cue-timings-and-settings-parsing) for a complete cue timing parsing procedure.

Now for a cue timing "00:11.000 --> 00:13.000".

- The standard assigns it as "11 seconds to 13 seconds".

- Current `parseTime` gives "0000-01-01 00:11:00 +0000 UTC  -->  0000-01-01 00:13:00 +0000 UTC", which means "11 minutes to 13 minutes".

Hope it helps.

**Comment by martinlindhe** [comment]
Hi @chen-chao and thanks for the report!
Issue should be resolved in https://github.com/martinlindhe/subtitles/commit/6299e69ede1b7cc1830817b670dba62113b2791c and released in version 0.1.8

**Comment by chen-chao** [comment]
OK. Thanks for the quick fix.
