### ISSUE TITLE
encoding error for parse

### ISSUE THREAD

**Issue by tramhao** [martinlindhe/subtitles#6]
We are working on a project gomu and using subtitle lib to parse the lyrics. When I use Newfromsrt(lyricstring), everything is fine, when i use parse([]byte(lyricstring)), english lyrics are all right, but chinese lyrics are displaying with wrong encoding.  what is the possible cause and direction to solve it? Thanks!

**Comment by martinlindhe** [comment]
What text encoding is used?

Could you provide a sample file please?

**Comment by tramhao** [comment]
[1.zh-CN.srt.txt](https://github.com/martinlindhe/subtitles/files/6043394/1.zh-CN.srt.txt)
For example the above file. The file is in utf8 encoding.

I try to debug my problem and found that the problem happened when convert to utf8 in parse function. During testing, the file is rocognized as latin1 encoding. 

By the way, in my application I didn't load this srt from file, but from embeded uslt frame of mp3. After reading, it's a string. Is this a probable cause for the problem?

The project link is :https://github.com/issadarkthing/gomu

**Comment by martinlindhe** [comment]
Indeed there is a bug in subtitles here. I'm looking into it!

It is destroying the input encoding for some reason. Thanks for reporting!

**Comment by martinlindhe** [comment]
https://github.com/martinlindhe/subtitles/releases/tag/0.2.1 has been released with a fix for better utf8 auto detection

**Comment by tramhao** [comment]
Here I would like to confirm that the new release fix my issue. Now subtitles.Parse([]data(lyricString)) works with chinese characters.

**Comment by martinlindhe** [comment]
@tramhao I am happy to hear, thank you for the follow up!
