### ISSUE TITLE
Merge two files

### ISSUE THREAD

**Issue by kqvanity** [martinlindhe/subtitles#7]
Can you add support to merge two srt files. It'd be ideal to lets say parse the two of them, determine the LCD then interleave the two files together for a bilingual experience for example.
So far I've managed to do that but by manually tailing the srt files, convert the latest timestamp to milliseconds, then shifting it and concatenating the output file with another srt file.
Thanks

**Comment by martinlindhe** [comment]
You could easily whip something up like that using the go api.

Start by parsing two srt's using NewFromSrt [1], then just merge captions, sort them by time and write them out to disk.

1: https://pkg.go.dev/github.com/martinlindhe/subtitles#NewFromSRT
